# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
